gitlabUrl: https://gitlab.asan

runnerToken: glrt-qGwigdz9tXeYxy7NkdB9
rbac:
  create: true

certsSecretName: gitlab-runner-tls

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:16.04"
    [[runners.kubernetes.volumes.pvc]]
      mount_path = "/cache/maven.repository"
      name = "gitlab-runner-cache-pvc"
