expose:
  tls:
    certSource: secret
    secret:
      secretName: "harbor-ingress-tls"
  ingress:
    hosts:
      core: harbor.asan
externalURL: https://harbor.asan

persistence:
  persistentVolumeClaim:
    registry:
      storageClass: "nfs-csi"
    jobservice:
      jobLog:
        storageClass: "nfs-csi"
    database:
      storageClass: "nfs-csi"
    redis:
      storageClass: "nfs-csi"
    trivy:
      storageClass: "nfs-csi"
